paths:
  data_dir: "/workspace/work/BrainWhisper/data/raw/hdf5_data_final/"
  processed_dir: "data/processed"

audio:
  tts_model: "tts_models/en/ljspeech/tacotron2-DDC"

embedding:
    model: 'base'

training:
  batch_size: 4
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 0  
  device: "cuda"  # or "cpu"

